version: 2
jobs:
  build_and_test_contracts:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/lendo
    steps:
      - checkout
      - restore_cache:
          keys:
            - loan-contract-dependencies-{{ checksum "packages/loan-contract/package.json" }}
      - run:
          working_directory: ~/lendo/packages/loan-contract/
          command: yarn install
      - run:
          name: Run smart contract tests
          working_directory: ~/lendo/packages/loan-contract/
          command: yarn test
      - save_cache:
          paths:
            - packages/loan-contract/node_modules
          key: loan-contract-dependencies-{{ checksum "packages/loan-contract/package.json" }}

  build_and_test_dapp:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/lendo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dapp-dependencies-{{ checksum "packages/dapp/package.json" }}
      - run:
          working_directory: ~/lendo/packages/dapp/
          command: yarn install
      - run:
          name: Run dapp tests
          working_directory: ~/lendo/packages/dapp/
          command: yarn test
      - save_cache:
          paths:
            - packages/dapp/node_modules
          key: dapp-dependencies-{{ checksum "packages/dapp/package.json" }}

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test_contracts
      - build_and_test_dapp
