version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0

    working_directory: ~/lendo

    steps:
      - checkout:
          path: ~/lendo

      - restore_cache:
          keys:
            - dapp-dependencies-{{ checksum "packages/dapp/package.json" }}
      - restore_cache:
          keys:
            - loan-contract-dependencies-{{ checksum "packages/loan-contract/package.json" }}

      - run: yarn install

      - save_cache:
          paths:
            - packages/dapp/node_modules
          key: dapp-dependencies-{{ checksum "packages/dapp/package.json" }}
      - save_cache:
          paths:
            - packages/loan-contract/node_modules
          key: loan-contract-dependencies-{{ checksum "packages/loan-contract/package.json" }}

      - run:
          name: Run smart contract tests
          working_directory: ~/lendo/packages/loan-contract/
          command: yarn test

      - run:
          name: Run dapp tests
          working_directory: ~/lendo/packages/dapp/
          command: yarn test
